-- Execute este arquivo uma única vez no SQL Editor do projeto Supabase.
-- Depois convide o usuário administrador e cadastre o e-mail dele na tabela
-- privada catalog_admin_emails antes de publicar o painel.

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.catalog_admin_emails (
  email text primary key check (email = lower(trim(email)) and position('@' in email) > 1),
  created_at timestamptz not null default now()
);

revoke all on private.catalog_admin_emails from public, anon, authenticated;
grant usage on schema private to authenticated;
grant select on private.catalog_admin_emails to authenticated;
alter table private.catalog_admin_emails enable row level security;
drop policy if exists "Admin checks own catalog access" on private.catalog_admin_emails;
create policy "Admin checks own catalog access" on private.catalog_admin_emails
for select to authenticated
using (
  email = lower((select auth.jwt()->>'email'))
  and coalesce((select (auth.jwt()->>'is_anonymous')::boolean), false) is false
);

create or replace function private.is_catalog_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select
    coalesce((select (auth.jwt()->>'is_anonymous')::boolean), false) is false
    and exists (
      select 1
      from private.catalog_admin_emails admins
      where admins.email = lower((select auth.jwt()->>'email'))
    );
$$;

revoke all on function private.is_catalog_admin() from public, anon;
grant execute on function private.is_catalog_admin() to authenticated;

create table if not exists public.catalog_settings (
  id smallint primary key default 1 check (id = 1),
  seller_name text not null default 'Samuel Yamaha',
  whatsapp text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id text primary key default gen_random_uuid()::text,
  name text not null check (length(trim(name)) > 0),
  description text not null default '',
  icon text not null default '🏍️',
  image_url text not null default '',
  image_path text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.motos (
  id text primary key default gen_random_uuid()::text,
  category_id text not null references public.categories(id) on delete restrict,
  name text not null check (length(trim(name)) > 0),
  year_model text not null default '',
  description text not null default '',
  active boolean not null default true,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moto_photos (
  id text primary key default gen_random_uuid()::text,
  moto_id text not null references public.motos(id) on delete cascade,
  url text not null,
  path text not null,
  is_primary boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.plans (
  id text primary key default gen_random_uuid()::text,
  moto_id text not null references public.motos(id) on delete cascade,
  installments integer not null check (installments > 0),
  installment_value numeric(12,2) not null check (installment_value > 0),
  label text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  moto_id text references public.motos(id) on delete set null,
  plan_id text references public.plans(id) on delete set null,
  moto_name text not null,
  installments integer not null check (installments > 0),
  installment_value numeric(12,2) not null check (installment_value > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_categories_order on public.categories(active, sort_order);
create index if not exists idx_motos_category on public.motos(category_id, active, sort_order);
create index if not exists idx_photos_moto on public.moto_photos(moto_id, sort_order);
create index if not exists idx_plans_moto on public.plans(moto_id, active, sort_order);
create index if not exists idx_leads_created on public.leads(created_at desc);

create or replace function public.replace_moto_plans(p_moto_id text, p_plans jsonb)
returns setof public.plans
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
begin
  if not (select private.is_catalog_admin()) then
    raise exception 'Acesso não autorizado';
  end if;
  if not exists (select 1 from public.motos where id = p_moto_id) then
    raise exception 'Moto não encontrada';
  end if;
  if jsonb_typeof(p_plans) <> 'array' or jsonb_array_length(p_plans) = 0 then
    raise exception 'Cadastre pelo menos um plano';
  end if;

  delete from public.plans where moto_id = p_moto_id;
  insert into public.plans (moto_id, installments, installment_value, label, active, sort_order)
  select
    p_moto_id,
    (item->>'installments')::integer,
    (item->>'installment_value')::numeric,
    coalesce(item->>'label', ''),
    coalesce((item->>'active')::boolean, true),
    coalesce((item->>'sort_order')::integer, ordinality::integer)
  from jsonb_array_elements(p_plans) with ordinality as rows(item, ordinality);

  return query select p.* from public.plans p where p.moto_id = p_moto_id order by p.sort_order, p.installments;
end;
$$;

revoke all on function public.replace_moto_plans(text, jsonb) from public, anon;
grant execute on function public.replace_moto_plans(text, jsonb) to authenticated;

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists categories_updated_at on public.categories;
create trigger categories_updated_at before update on public.categories for each row execute function public.set_updated_at();
drop trigger if exists motos_updated_at on public.motos;
create trigger motos_updated_at before update on public.motos for each row execute function public.set_updated_at();
drop trigger if exists plans_updated_at on public.plans;
create trigger plans_updated_at before update on public.plans for each row execute function public.set_updated_at();
drop trigger if exists settings_updated_at on public.catalog_settings;
create trigger settings_updated_at before update on public.catalog_settings for each row execute function public.set_updated_at();

alter table public.catalog_settings enable row level security;
alter table public.categories enable row level security;
alter table public.motos enable row level security;
alter table public.moto_photos enable row level security;
alter table public.plans enable row level security;
alter table public.leads enable row level security;

drop policy if exists "Public can read settings" on public.catalog_settings;
create policy "Public can read settings" on public.catalog_settings for select to anon using (true);
drop policy if exists "Admin can read settings" on public.catalog_settings;
create policy "Admin can read settings" on public.catalog_settings for select to authenticated using ((select private.is_catalog_admin()));
drop policy if exists "Admin can update settings" on public.catalog_settings;
create policy "Admin can update settings" on public.catalog_settings for update to authenticated using ((select private.is_catalog_admin())) with check ((select private.is_catalog_admin()));
drop policy if exists "Admin can insert settings" on public.catalog_settings;
create policy "Admin can insert settings" on public.catalog_settings for insert to authenticated with check (id = 1 and (select private.is_catalog_admin()));

drop policy if exists "Public reads active categories" on public.categories;
create policy "Public reads active categories" on public.categories for select to anon using (active);
drop policy if exists "Admin manages categories" on public.categories;
create policy "Admin manages categories" on public.categories for all to authenticated using ((select private.is_catalog_admin())) with check ((select private.is_catalog_admin()));

drop policy if exists "Public reads active motos" on public.motos;
create policy "Public reads active motos" on public.motos for select to anon using (
  active and exists (select 1 from public.categories c where c.id = motos.category_id and c.active)
);
drop policy if exists "Admin manages motos" on public.motos;
create policy "Admin manages motos" on public.motos for all to authenticated using ((select private.is_catalog_admin())) with check ((select private.is_catalog_admin()));

drop policy if exists "Public reads photos of active motos" on public.moto_photos;
create policy "Public reads photos of active motos" on public.moto_photos for select to anon using (
  exists (
    select 1 from public.motos m join public.categories c on c.id = m.category_id
    where m.id = moto_photos.moto_id and m.active and c.active
  )
);
drop policy if exists "Admin manages photos" on public.moto_photos;
create policy "Admin manages photos" on public.moto_photos for all to authenticated using ((select private.is_catalog_admin())) with check ((select private.is_catalog_admin()));

drop policy if exists "Public reads active plans" on public.plans;
create policy "Public reads active plans" on public.plans for select to anon using (
  active and exists (
    select 1 from public.motos m join public.categories c on c.id = m.category_id
    where m.id = plans.moto_id and m.active and c.active
  )
);
drop policy if exists "Admin manages plans" on public.plans;
create policy "Admin manages plans" on public.plans for all to authenticated using ((select private.is_catalog_admin())) with check ((select private.is_catalog_admin()));

drop policy if exists "Public creates leads" on public.leads;
create policy "Public creates leads" on public.leads for insert to anon with check (
  exists (
    select 1
    from public.plans p
    join public.motos m on m.id = p.moto_id
    join public.categories c on c.id = m.category_id
    where p.id = leads.plan_id
      and m.id = leads.moto_id
      and m.name = leads.moto_name
      and p.installments = leads.installments
      and p.installment_value = leads.installment_value
      and p.active and m.active and c.active
  )
);
drop policy if exists "Admin reads leads" on public.leads;
create policy "Admin reads leads" on public.leads for select to authenticated using ((select private.is_catalog_admin()));
drop policy if exists "Admin deletes leads" on public.leads;
create policy "Admin deletes leads" on public.leads for delete to authenticated using ((select private.is_catalog_admin()));

revoke all on public.catalog_settings, public.categories, public.motos, public.moto_photos, public.plans, public.leads from anon, authenticated;
grant select on public.catalog_settings, public.categories, public.motos, public.moto_photos, public.plans to anon, authenticated;
grant insert (moto_id, plan_id, moto_name, installments, installment_value) on public.leads to anon;
grant select, insert, update, delete on public.catalog_settings, public.categories, public.motos, public.moto_photos, public.plans, public.leads to authenticated;
grant usage, select on sequence public.leads_id_seq to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('motorcycle-images', 'motorcycle-images', true, 8388608, array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public reads motorcycle images" on storage.objects;
create policy "Public reads motorcycle images" on storage.objects for select to anon, authenticated using (bucket_id = 'motorcycle-images');
drop policy if exists "Admin uploads motorcycle images" on storage.objects;
create policy "Admin uploads motorcycle images" on storage.objects for insert to authenticated with check (bucket_id = 'motorcycle-images' and (select private.is_catalog_admin()));
drop policy if exists "Admin updates motorcycle images" on storage.objects;
create policy "Admin updates motorcycle images" on storage.objects for update to authenticated using (bucket_id = 'motorcycle-images' and (select private.is_catalog_admin())) with check (bucket_id = 'motorcycle-images' and (select private.is_catalog_admin()));
drop policy if exists "Admin deletes motorcycle images" on storage.objects;
create policy "Admin deletes motorcycle images" on storage.objects for delete to authenticated using (bucket_id = 'motorcycle-images' and (select private.is_catalog_admin()));

insert into public.catalog_settings (id, seller_name, whatsapp)
values (1, 'Samuel Yamaha', '5569999999999')
on conflict (id) do nothing;

insert into public.categories (name, description, icon, active, sort_order)
select seed.name, seed.description, seed.icon, true, seed.sort_order
from (values
  ('Street', 'Motos urbanas e versáteis', '🏍️', 1),
  ('Scooter', 'Praticidade para o dia a dia', '🛵', 2),
  ('Naked', 'Design e desempenho', '🏍️', 3),
  ('Trail', 'Aventura em qualquer terreno', '🏍️', 4),
  ('Esportiva', 'Alta performance e esportividade', '🏁', 5)
) as seed(name, description, icon, sort_order)
where not exists (select 1 from public.categories c where lower(c.name) = lower(seed.name));

insert into public.motos (category_id, name, year_model, description, active, featured, sort_order)
select c.id, seed.name, '2026', seed.description, true, seed.featured, seed.sort_order
from (values
  ('Trail', 'Lander 250', 'A Lander 250 é feita para quem busca aventura e desempenho em qualquer terreno. Motor potente, design moderno e tecnologia que garante segurança e conforto em todas as jornadas.', true, 1),
  ('Street', 'Fazer 250', 'Uma Yamaha equilibrada para uso urbano, com conforto, economia e desempenho para o dia a dia.', true, 2),
  ('Scooter', 'NMAX 160', 'Scooter prática e confortável para mobilidade urbana.', true, 3),
  ('Naked', 'MT-03', 'Naked de visual marcante, proposta esportiva e agilidade para a cidade.', false, 4),
  ('Esportiva', 'R15', 'Esportiva leve, moderna e com visual inspirado nas motos de competição.', false, 5)
) as seed(category_name, name, description, featured, sort_order)
join public.categories c on lower(c.name) = lower(seed.category_name)
where not exists (select 1 from public.motos m where m.category_id = c.id and lower(m.name) = lower(seed.name));

insert into public.plans (moto_id, installments, installment_value, active, sort_order)
select m.id, seed.installments, seed.installment_value, true, seed.sort_order
from (values
  ('Lander 250', 36, 899.90::numeric, 1),
  ('Lander 250', 45, 749.90::numeric, 2),
  ('Lander 250', 58, 599.90::numeric, 3),
  ('Lander 250', 70, 519.90::numeric, 4),
  ('Lander 250', 80, 469.90::numeric, 5),
  ('Fazer 250', 80, 439.90::numeric, 1),
  ('NMAX 160', 80, 379.90::numeric, 1),
  ('MT-03', 80, 579.90::numeric, 1),
  ('R15', 80, 448.99::numeric, 1)
) as seed(moto_name, installments, installment_value, sort_order)
join public.motos m on lower(m.name) = lower(seed.moto_name)
where not exists (
  select 1 from public.plans p where p.moto_id = m.id and p.installments = seed.installments
);
